# Generated by Django 2.1.7 on 2019-03-18 20:21

from django.db import migrations
import questioner.apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', questioner.apps.user.models.CustomUserManager()),
            ],
        ),
    ]
